version: '3.8'

services:
  clima-cep-api:
    build:
      context: .
      dockerfile: src/backend/Clima.Cep.Api/Dockerfile
    container_name: clima-cep-api
    ports:
      - "5137:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
    networks:
      - climacepnetwork

  clima-cep-app:
    build:
      context: ./src/frontend/Clima.Cep.App
      dockerfile: Dockerfile
    container_name: clima-cep-app
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://clima-cep-api:80/api
      - NODE_ENV=production
    networks:
      - climacepnetwork
    depends_on:
      - clima-cep-api

networks:
  climacepnetwork:
    driver: bridge
