version: '3.8'

services:
  clima-cep-api:
    build:
      context: .
      dockerfile: src/backend/Clima.Cep.Api/Dockerfile
    container_name: clima-cep-api
    ports:
      - "5137:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
    networks:
      - climacepnetwork

networks:
  climacepnetwork:
    driver: bridge
